alias ss='doas dnf install -y'
alias rr='doas dnf remove -y'
alias l='ls -a'
alias upd='doas dnf update -y && doas dnf upgrade -y && flatpak update -y'
alias c='clear'
alias ff='fastfetch'
alias v='vim'
alias ai='ollama run llama3.1'
